### ISSUE TITLE
Error when I try connect to server in Flutter 1.20.

### ISSUE THREAD

**Issue by fipooo** [blackhorse-one/stomp_dart_client#26] opened 2020-08-07 07:18 UTC
Hi, this error give me when I try connect to the server. How to fix it?

```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: type '_Uint8ArrayView' is not a subtype of type 'String'
#0      StompHandler._onData (package:stomp_dart_client/stomp_handler.dart:170:36)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
#7      _HandleErrorStream._handleData (dart:async/stream_pipe.dart:266:10)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#12     _BufferingStreamSubscription._sendData (dart:asyn<…>

```

**Comment by KammererTob** [comment] 2020-08-09 20:14
Hey,

to what type of server are you connecting? And what is the data you are receiving? It seems to be a byte array. I know what the issue is, but i want to build some unit-tests around the issue.

**Comment by KammererTob** [comment] 2020-08-13 14:48
I just pushed a fix for this issue. Will be resolved with the next release.

**Closed by KammererTob** 2020-08-13 14:48 UTC
